apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: macvice
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/barryw/macvice-website
    newTag: latest
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: macvice
